### ISSUE TITLE
Full source

### ISSUE THREAD

**Issue by ReaGed** [SaturnsVoid/GoBot2#4]
@SaturnsVoid  Greetings!

Can you share the full source of the project?

```
/taskmgr
/syslogs
/build
/dbuild
/tools
/account

... etc
```

**Comment by 1am3** [comment]
Hello. Thank you!
Where can I find a complete project?

**Comment by SaturnsVoid** [comment]
I left it out to make it harder for people to use it for illicit actions. If you know anything about how the code works you can make your own control panel.
